spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://config-server:8088"

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans